# Generated by Django 3.2.5 on 2023-04-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('birthdate', models.DateField()),
                ('photo', models.ImageField(upload_to='')),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
