# Generated by Django 3.2.5 on 2023-04-02 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memories_app', '0002_auto_20230402_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='user_id',
            new_name='user',
        ),
    ]
