# Generated by Django 4.1.7 on 2023-05-08 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories_app', '0003_date_exact_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='year',
            field=models.PositiveIntegerField(default=2000),
            preserve_default=False,
        ),
    ]
