# Generated by Django 4.1.7 on 2023-05-08 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memories_app', '0004_date_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date',
            name='exact_date',
        ),
    ]
