# Generated by Django 4.1.7 on 2023-04-03 22:35

from django.db import migrations, models
import memories_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('memories_app', '0005_location_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(upload_to=memories_app.models.user_directory_path),
        ),
    ]
