# Generated by Django 4.1.7 on 2023-05-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories_app', '0005_remove_date_exact_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='display_option',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='date',
            name='displayed_text',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
