# Generated by Django 4.1.7 on 2023-05-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories_app', '0006_date_display_option_date_displayed_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='displayed_text',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
