# Generated by Django 4.1.7 on 2023-04-11 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memories_app', '0007_user_last_login'),
    ]

    operations = [
    ]
