# Generated by Django 4.1.7 on 2023-05-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories_app', '0009_customuser_alter_comments_user_alter_like_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
