# Generated by Django 4.1.7 on 2023-05-02 17:33

from django.db import migrations, models
import django.db.models.deletion
import memories_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('memories_app', '0010_alter_story_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=memories_app.models.user_directory_path)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='memories_app.story')),
            ],
        ),
    ]
