# Generated by Django 4.1.7 on 2023-05-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories_app', '0011_storyphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyphoto',
            name='photo',
            field=models.ImageField(upload_to='images/story_photos'),
        ),
    ]
