version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:5500
    volumes:
      - .:/app
    ports:
      - 5500:5500
    environment:
      - DB_NAME=memories
      - DB_USER=root
      - DB_PASSWORD=Otosan01
      - DB_HOST=host.docker.internal
      - DB_PORT=3306
